// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace tarea7.Migrations
{
    [DbContext(typeof(DetencionContexto))]
    partial class DetencionContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Detencion", b =>
                {
                    b.Property<int>("IdDentencion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaDetencion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Latitud")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Longitud")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumPasaporte")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdDentencion");

                    b.ToTable("Detencion");
                });
#pragma warning restore 612, 618
        }
    }
}
